name: global_plug
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_svg:
  pinput:
  iconsax: ^0.0.8
  intl:
  intl_phone_field: 
  dotted_border: ^2.1.0
  file_picker: ^8.0.7
  fluttertoast: ^8.2.6
  open_file: ^3.3.2
  shared_preferences: ^2.3.2
  http:
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/

  
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf

  - family: OpenSans
    fonts:
      - asset: assets/fonts/OpenSans.ttf


  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
